on:
  - push
  - pull_request

jobs:
  test:
    name: "Test, typecheck and lint"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"

      - name: "Install Dependencies"
        run: pnpm install

      - name: "Audit"
        run: pnpm audit

      - name: "Typecheck"
        run: pnpm run typecheck

      - name: "Lint"
        run: pnpm run lint

      - name: "Check formatting"
        run: pnpm run check

      - name: "Test"
        run: pnpm --if-present run test
